apiVersion: v1
kind: Secret
metadata:
  name: stock-secrets
  namespace: stock-management
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASSWORD: CHANGE_ME
  JWT_SECRET: CHANGE_ME
  REFRESH_TOKEN_SECRET: CHANGE_ME
  ADMIN_EMAIL: admin@example.com
  ADMIN_PASSWORD: CHANGE_ME
  MAIL_HOST: smtp.example.com
  MAIL_USER: CHANGE_ME
  MAIL_PASSWORD: CHANGE_ME
  MAIL_FROM: no-reply@example.com
