apiVersion: v1
kind: Secret
metadata:
  name: stock-secrets
  labels: {{- include "stock.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  REFRESH_TOKEN_SECRET: {{ .Values.secrets.refreshTokenSecret | quote }}
  ADMIN_EMAIL: {{ .Values.secrets.adminEmail | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
  MAIL_HOST: {{ .Values.secrets.mailHost | quote }}
  MAIL_USER: {{ .Values.secrets.mailUser | quote }}
  MAIL_PASSWORD: {{ .Values.secrets.mailPassword | quote }}
  MAIL_FROM: {{ .Values.secrets.mailFrom | quote }}
